FROM python:latest
RUN mkdir PythonFiles
COPY BookRecommenderSystem_Cleaned.ipynb /PythonFiles/

# RUN pip install scikit-learn requests pandas numpy matplotlib seaborn plotly scipy bs4

WORKDIR /PythonFiles